---
- name: redhat | Rpm --import
  ansible.builtin.rpm_key:
    key: "{{ item.key }}"
    fingerprint: "{{ item.fingerprint }}"
    state: "{{ item.state }}"
  loop: "{{ _rpm_key }}"
  register: result
  until: result is succeeded

- name: redhat | Yum-config-manager --add-repo
  ansible.builtin.yum_repository:
    file: "{{ item.file }}"
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    enabled: "{{ item.enabled }}"
    priority: "{{ item.priority }}"
    module_hotfixes: "{{ item.module_hotfixes }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state }}"
  loop: "{{ _yum_repository }}"

- name: redhat | Yum versionlock delete
  community.general.yum_versionlock:
    name: "{{ item.name | regex_replace('^(.*)-[0-9]*:*[0-9]+\\..*$', '\\1-*') }}"
    state: "absent"
  loop: "{{ _yum }}"
  when: item.state == "present"
  changed_when: false
  failed_when: false

- name: redhat | Yum install
  ansible.builtin.yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ _yum }}"
  register: result
  until: result is succeeded
  notify:
    - Gitlab-ctl reconfigure
    - Systemctl restart gitlab-runsvdir.service

- name: redhat | Yum versionlock add
  community.general.yum_versionlock:
    name: "{{ item.name | regex_replace('^(.*)-[0-9]*:*[0-9]+\\..*$', '\\1-*') }}"
    state: "present"
  loop: "{{ _yum }}"
  when: item.state == "present"
  changed_when: false
  failed_when: false
