---

- name: Install required pip packages | rhel
  vars:
    ansible_python_interpreter: "python3"
  ansible.builtin.pip:
    name:
      - dataclasses

- name: rpm --import | rhel
  ansible.builtin.rpm_key:
    key: "{{ item.key }}"
    fingerprint: "{{ item.fingerprint }}"
    state: "{{ item.state }}"
  loop: "{{ _rpm_key }}"
  register: result
  until: result is succeeded

- name: yum-config-manager --add-repo | rhel
  ansible.builtin.yum_repository:
    file: "{{ item.file }}"
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    enabled: "{{ item.enabled }}"
    priority: "{{ item.priority }}"
    module_hotfixes: "{{ item.module_hotfixes }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state }}"
  loop: "{{ _yum_repository }}"

- name: yum versionlock delete | rhel
  community.general.yum_versionlock:
    name: "{{ item.name | regex_replace('^(.*)-[0-9]*:*[0-9]+\\..*$', '\\1-*') }}"
    state: "absent"
  loop: "{{ _yum }}"
  when: item.state == "present"
  changed_when: false
  failed_when: false

- name: yum install | rhel
  ansible.builtin.yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ _yum }}"
  register: result
  until: result is succeeded
  notify:
    - gitlab_ce | gitlab-ctl reconfigure
    - gitlab_ce | systemctl restart gitlab-runsvdir.service

- name: yum versionlock add | rhel
  community.general.yum_versionlock:
    name: "{{ item.name | regex_replace('^(.*)-[0-9]*:*[0-9]+\\..*$', '\\1-*') }}"
    state: "present"
  loop: "{{ _yum }}"
  when: item.state == "present"
  changed_when: false
  failed_when: false
