---
- hosts: all
  remote_user: root
  become: true
  gather_facts: yes
  roles:
    - name: buluma.bootstrap
    - name: buluma.timezone
    - name: buluma.setuptools
    - name: ansible-role-gitlab_ce
