---
- hosts: all
  remote_user: root
  become: true
  tasks:
    - name: Gitlab --version
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      ansible.builtin.command: gitlab --version
      register: result
      changed_when: result is not succeeded

    - name: Gitlab-rake gitlab:env:info
      ansible.builtin.command: gitlab-rake gitlab:env:info
      register: result
      changed_when: result is not succeeded
